version: '3.7'
services:
  crudpessoas-front:
    image: luizgustavoob/crudpessoas-front:latest
    ports:
      - "80:80"
    depends_on:
      - crudpessoas-api
  crudpessoas-api:
    image: luizgustavoob/crudpessoas-api:latest
    ports:
      - "8080:8080"
    